---
  name: get_config
  runner_type: "python-script"
  description: "Server configuration from PowerDNS API"
  entry_point: "get_config.py"
  parameters:
    server_id:
      type: string
      description: "Server name to query."
      required: true
      default: localhost
